/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  creator?: string | null;
  vectors?: Vector[] | null;
}
export interface Vector {
  name: string;
  vector_id: number;
  vector_rate: Uint128;
}
export type ExecuteMsg = string;
export type QueryMsg = {
  vectors: {};
} | {
  get_creator_ownership: {};
};
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}
export interface AllVectorsResponse {
  vectors: Vector[];
}