/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type HexBinary = string;
export interface InstantiateMsg {
  owner?: Addr | null;
  tee_config?: TeeSetup | null;
  tribute_address?: Addr | null;
  zk_config?: ZkSetup | null;
}
export interface TeeSetup {
  private_key: HexBinary;
  salt: HexBinary;
}
export interface ZkSetup {
  circuit: HexBinary;
}
export type ExecuteMsg = {
  update_config: {
    new_owner?: Addr | null;
    new_tee_config?: TeeSetup | null;
    new_tribute_address?: Addr | null;
  };
} | {
  offer: {
    cipher_text: HexBinary;
    ephemeral_pubkey: HexBinary;
    nonce: HexBinary;
    zk_proof: ZkProof;
  };
} | {
  offer_insecure: {
    tribute_input: TributeInputPayload;
    zk_proof: ZkProof;
  };
};
export interface ZkProof {
  proof: HexBinary;
  public_data: ZkProofPublicData;
  verification_key: HexBinary;
}
export interface ZkProofPublicData {
  merkle_root: HexBinary;
  public_key: HexBinary;
}
export interface TributeInputPayload {
  cu_hashes: HexBinary[];
  nominal_atto_qty: number;
  nominal_base_qty: number;
  owner: string;
  settlement_atto_amount: number;
  settlement_base_amount: number;
  settlement_currency: string;
  worldwide_day: string;
}
export type QueryMsg = {
  get_config: {};
} | {
  pubkey: {};
};
export interface ConfigResponse {
  tribute_address?: Addr | null;
}
export interface PubkeyResponse {
  public_key: HexBinary;
}