[package]
name          = "agent-common"
version       = { workspace = true }
edition       = { workspace = true }

[lib]
doctest      = false # disable doc tests

[dependencies]
cosmwasm-std     = { workspace = true }
cw-storage-plus  = { workspace = true }
serde            = { workspace = true }
schemars         = { workspace = true }
thiserror        = { workspace = true }
cosmwasm-schema = { workspace = true }

