/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export type Addr = string;
export interface InstantiateMsg {
  creator?: string | null;
  deficit: Decimal;
  nod?: Addr | null;
  price_oracle?: Addr | null;
  random_oracle?: Addr | null;
  token_allocator?: Addr | null;
  tribute?: Addr | null;
  vector?: Addr | null;
}
export type ExecuteMsg = {
  execute: {
    run_date?: number | null;
  };
} | {
  burn_all: {};
};
export type QueryMsg = {
  daily_runs: {};
} | {
  tributes_distribution: {};
} | {
  allocation: {};
};
export type Uint128 = string;
export interface AllocationResponse {
  pool_allocation: Uint128;
  total_allocation: Uint128;
}
export type RunType = "lysis" | "touch";
export interface DailyRunsResponse {
  data: DailyRunsData[];
}
export interface DailyRunsData {
  info: DailyRunInfo;
  runs_happened: number;
  timestamp: number;
}
export interface DailyRunInfo {
  data: RunInfo[];
  number_of_runs: number;
}
export interface RunInfo {
  assigned_tributes: number;
  assigned_tributes_sum: Uint128;
  pool_allocation: Uint128;
  pool_capacity: Uint128;
  pool_deficit: Uint128;
  run_type: RunType;
  total_allocation: Uint128;
  total_deficit: Uint128;
  vector_index: number;
}
export interface TributesDistributionResponse {
  data: TributesDistributionData[];
}
export interface TributesDistributionData {
  key: string;
  tribute_id: string;
}