/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  access_list: AccessMsg[];
  gratis_contract: string;
  nod_contract: string;
  price_oracle_contract: string;
  promis_contract: string;
}
export interface AccessMsg {
  address: string;
  permissions: AccessPermissions;
}
export interface AccessPermissions {
  can_mint_gratis: boolean;
  can_mint_promis: boolean;
  note?: string | null;
}
export type ExecuteMsg = {
  mine: {
    amount: Uint128;
    recipient: string;
    token_type: TokenType;
  };
} | {
  mine_gratis_with_nod: {
    nod_token_id: string;
  };
} | {
  add_to_access_list: {
    address: string;
    permissions: AccessPermissions;
  };
} | {
  remove_from_access_list: {
    address: string;
  };
} | {
  update_permissions: {
    address: string;
    permissions: AccessPermissions;
  };
} | {
  transfer_admin: {
    new_admin: string;
  };
} | {
  update_contracts: {
    gratis_contract?: string | null;
    nod_contract?: string | null;
    price_oracle_contract?: string | null;
    promis_contract?: string | null;
  };
};
export type Uint128 = string;
export type TokenType = "gratis" | "promis";
export type QueryMsg = {
  config: {};
} | {
  access_permissions: {
    address: string;
  };
} | {
  access_list: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  can_mint: {
    address: string;
    token_type: TokenType;
  };
};
export type Addr = string;
export interface AccessListResponse {
  addresses: [Addr, AccessPermissions][];
}
export interface AccessPermissionsResponse {
  address: Addr;
  permissions?: AccessPermissions | null;
}
export interface CanMintResponse {
  can_mint: boolean;
  reason?: string | null;
}
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  admin: Addr;
  gratis_contract: Addr;
  nod_contract: Addr;
  price_oracle_contract: Addr;
  promis_contract: Addr;
}