/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  publish: {
    deployment: Deployment;
  };
} | {
  ownable: Action;
};
export type Addr = string;
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Deployment {
  commit_id: string;
  contracts: ContractInfo[];
  is_latest: boolean;
}
export interface ContractInfo {
  address: Addr;
  name: string;
}
export type QueryMsg = {
  all_deployments: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  get_deployment: {
    commit_id?: string | null;
  };
} | {
  ownable: [];
};
export interface AllDeploymentsResponse {
  deployments: Deployment[];
}
export interface GetDeploymentResponse {
  deployment: Deployment;
}
export type Binary = string;