/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  random_value?: number | null;
}
export type ExecuteMsg = {
  set_random: {
    random_value?: number | null;
  };
};
export type QueryMsg = {
  random_value: {
    count_values: number;
    from_range: number;
    to_range: number;
  };
};
export interface RandomResponse {
  random_values: number[];
}