[package]
name = "outbe-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cosmwasm-std = { workspace = true }
thiserror = { workspace = true }
cosmwasm-schema = { workspace = true }
chrono = { version = "0.4.41", default-features = false }
blake3 = { workspace = true }
bs58 = { workspace = true }
serde_json = "1.0.141"

