/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type DayType = "green" | "red";
export type Decimal = string;
export type Denom = {
  native: string;
} | {
  cw20: Addr;
} | {
  fiat: Currency;
};
export type Addr = string;
export type Currency = "usd" | "eur";
export interface InstantiateMsg {
  creator?: string | null;
  initial_price: TokenPairPrice;
}
export interface TokenPairPrice {
  day_type: DayType;
  price: Decimal;
  token1: Denom;
  token2: Denom;
}
export type ExecuteMsg = {
  update_price: {
    token_pair_price: TokenPairPrice;
  };
};
export type QueryMsg = {
  get_price: {};
} | {
  get_creator_ownership: {};
};
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}