name: Project Build

on:
  pull_request:

jobs:
  wasm:
    name: Optimized Wasm
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/outbe/outbe-wasm-builder:0.2.2-nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - run: rustc --version
      - run: rustup target add wasm32-unknown-unknown
      - name: Make Optimized build
        run: |
          optimize.sh .

  wasm-sei:
    name: Optimized Wasm SEI
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/outbe/outbe-wasm-sei-builder:0.1.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Make Optimized build
        run: |
          optimize.sh .
