name: Project Build

on:
  pull_request:

jobs:
  wasm:
    name: Optimized Wasm
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/outbe/outbe-wasm-builder:0.1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-08-20
          target: wasm32-unknown-unknown
          override: true

      - name: Make Optimized build
        run: |
          optimize.sh .
