name: Code Coverage

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    name: Code Coverage Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install 1.83 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.83.0
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 \
            --exclude-files 'contracts/*/examples/*' \
            --exclude-files 'integration-tests/*' \
            --out xml --output-dir ./coverage/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/cobertura.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Coverage check
        uses: 5monkeys/cobertura-action@master
        with:
          path: ./coverage/cobertura.xml
          minimum_coverage: 75
          fail_below_threshold: true
          show_missing: true
          only_changed_files: false
