name: Deploy

on:
  workflow_dispatch:
    inputs:
      is_latest:
        description: 'Mark as latest'
        required: false
        type: boolean

env:
  # Chain configuration
  CHAIN_ID: outbe-devnet-1
  FEE_DENOM: unit
  RPC: https://rpc.dev.outbe.net

  CONTRACT_REGISTRY_CONTRACT_ADDRESS: "outbe1pu6e36nugjxv3w2tcvxgld39y5kx3zz6l74dwxyyytx9cz5xwg5s4sknnl"

jobs:
  deploy:
    name: Optimize & Deploy
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/outbe/outbe-wasm-builder:0.1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Configure wallet
        env:
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
        run: |
          outbe-noded keys import-hex ci $WALLET_PRIVATE_KEY --keyring-backend test
          OWNER_ADDRESS=$(outbe-noded keys show ci --keyring-backend test --output json | jq -r '.address')
          echo "OWNER_ADDRESS=$OWNER_ADDRESS" >> $GITHUB_ENV

      - name: Make Optimized build
        run: |
          optimize.sh .

      - name: Deploy CWs
        run: |
          CW20_CODE_ID=$(./scripts/store_code.sh artifacts/cw20_copy.wasm)
          echo "CW20_CODE_ID=$CW20_CODE_ID" >> $GITHUB_ENV

      - name: Deploy wUSDC
        run: |
          INIT_PAYLOAD=$(jq -n --arg minter $OWNER_ADDRESS --from-file ./contracts/cw20/fixtures/wusdc_init.json)
          WUSDC_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "wUSDC" $CW20_CODE_ID "$INIT_PAYLOAD")
          echo "WUSDC_CONTRACT_ADDRESS=$WUSDC_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Deploy Price Oracle
        run: |
          PRICE_ORACLE_CODE_ID=$(./scripts/store_code.sh artifacts/price_oracle.wasm)
          INIT_PAYLOAD=$(jq -n --arg usdc_address $WUSDC_CONTRACT_ADDRESS --from-file ./contracts/price-oracle/fixtures/init.json)
          PRICE_ORACLE_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Price Oracle" $PRICE_ORACLE_CODE_ID "$INIT_PAYLOAD")
          echo "PRICE_ORACLE_CONTRACT_ADDRESS=$PRICE_ORACLE_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Deploy Token Allocator
        run: |
          TOKEN_ALLOCATOR_CODE_ID=$(./scripts/store_code.sh artifacts/token_allocator.wasm)
          INIT_PAYLOAD=$(jq -n --from-file ./contracts/token-allocator/fixtures/init.json)
          TOKEN_ALLOCATOR_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Token Allocator" $TOKEN_ALLOCATOR_CODE_ID "$INIT_PAYLOAD")
          echo "TOKEN_ALLOCATOR_CONTRACT_ADDRESS=$TOKEN_ALLOCATOR_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Deploy Vector
        run: |
          VECTOR_CODE_ID=$(./scripts/store_code.sh artifacts/vector.wasm)
          INIT_PAYLOAD=$(jq -n --from-file ./contracts/vector/fixtures/init.json)
          VECTOR_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Vector" $VECTOR_CODE_ID "$INIT_PAYLOAD")
          echo "VECTOR_CONTRACT_ADDRESS=$VECTOR_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Deploy Tribute Factory
        run: |
          TRIBUTE_FACTORY_CODE_ID=$(./scripts/store_code.sh artifacts/tribute_factory.wasm)
          INIT_PAYLOAD=$(jq -n --from-file ./contracts/tribute-factory/fixtures/init.json)
          TRIBUTE_FACTORY_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Tribute Factory" $TRIBUTE_FACTORY_CODE_ID "$INIT_PAYLOAD")
          echo "TRIBUTE_FACTORY_CONTRACT_ADDRESS=$TRIBUTE_FACTORY_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Deploy Tribute
        run: |
          TRIBUTE_CODE_ID=$(./scripts/store_code.sh artifacts/tribute.wasm)
          INIT_PAYLOAD=$(jq -n --arg price_oracle $PRICE_ORACLE_CONTRACT_ADDRESS --arg minter $TRIBUTE_FACTORY_CONTRACT_ADDRESS --from-file ./contracts/tribute/fixtures/init.json)
          TRIBUTE_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Tribute" $TRIBUTE_CODE_ID "$INIT_PAYLOAD")
          echo "TRIBUTE_CONTRACT_ADDRESS=$TRIBUTE_CONTRACT_ADDRESS" >> $GITHUB_ENV
          
          echo "Link Tribute Factory and Tribute contracts"
          UPDATE_PAYLOAD=$(jq -n --arg tribute_address $TRIBUTE_CONTRACT_ADDRESS -f ./contracts/tribute-factory/fixtures/update-tribute-address.json)
          ./scripts/execute_tx.sh $TRIBUTE_FACTORY_CONTRACT_ADDRESS "$UPDATE_PAYLOAD"      

      - name: Deploy Nod
        run: |
          NOD_CODE_ID=$(./scripts/store_code.sh artifacts/nod.wasm)
          INIT_PAYLOAD=$(jq -n --from-file ./contracts/nod/fixtures/init.json)
          NOD_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Nod" $NOD_CODE_ID "$INIT_PAYLOAD")
          echo "NOD_CONTRACT_ADDRESS=$NOD_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Deploy Metadosis
        run: |
          METADOSIS_CODE_ID=$(./scripts/store_code.sh artifacts/metadosis.wasm)
          INIT_PAYLOAD=$(jq -n --arg price_oracle_address $PRICE_ORACLE_CONTRACT_ADDRESS --arg vector_address $VECTOR_CONTRACT_ADDRESS --arg tribute_address $TRIBUTE_CONTRACT_ADDRESS --arg nod_address $NOD_CONTRACT_ADDRESS --arg token_allocator_address $TOKEN_ALLOCATOR_CONTRACT_ADDRESS --from-file ./contracts/metadosis/fixtures/init.json)
          METADOSIS_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Metadosis" $METADOSIS_CODE_ID "$INIT_PAYLOAD")
          echo "METADOSIS_CONTRACT_ADDRESS=$METADOSIS_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Print output
        run: |
          echo "Deploy output:"
          env | sort | grep -E 'CODE_ID|ADDRESS' > output.txt
          cat output.txt

      - name: Update Contract Registry
        run: |
          COMMIT_ID=${{ github.sha }}
          IS_LATEST=${{ inputs.is_latest }} 
          echo "Updating Contract Registry with commit=$COMMIT_ID and latest=$IS_LATEST"
          CONTRACTS=$(./scripts/parse_contracts.sh output.txt)
          UPDATE_PAYLOAD=$(jq -n --arg commit_id $COMMIT_ID --argjson contracts "$CONTRACTS" --argjson is_latest $IS_LATEST --from-file ./contracts/contract-registry/fixtures/publish.json)
          ./scripts/execute_tx.sh $CONTRACT_REGISTRY_CONTRACT_ADDRESS "$UPDATE_PAYLOAD"

      - name: Send output
        id: sendoutput
        run: |
          cat output.txt >> "$GITHUB_OUTPUT"
