name: Deploy Registry Outbe-Chain

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment

env:
  FEE_DENOM: unit
  BINARY: outbe-chaind

jobs:
  deploy:
    name: Optimize & Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      RPC: ${{ vars.RPC }}
      CHAIN_ID: ${{ vars.CHAIN_ID }}
    container:
      image: ghcr.io/outbe/outbe-wasm-sei-builder:0.1.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Configure wallet
        env:
          WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
        run: |
          echo $WALLET_MNEMONIC | $BINARY keys add ci --keyring-backend test --recover
          OWNER_ADDRESS=$($BINARY keys show ci --keyring-backend test --output json | jq -r '.address')
          echo "OWNER_ADDRESS=$OWNER_ADDRESS" >> $GITHUB_ENV

      - name: Make Optimized build
        run: |
          optimize.sh .

      - name: Deploy Contract Registry
        run: |
          CONTRACT_REGISTRY_CODE_ID=$(./scripts/store_code.sh artifacts/contract_registry.wasm)
          echo "CONTRACT_REGISTRY_CODE_ID=$CONTRACT_REGISTRY_CODE_ID" >> $GITHUB_ENV
          CONTRACT_REGISTRY_CONTRACT_ADDRESS=$(./scripts/init_contract.sh "Contract Registry" $CONTRACT_REGISTRY_CODE_ID "{}")
          echo "CONTRACT_REGISTRY_CONTRACT_ADDRESS=$CONTRACT_REGISTRY_CONTRACT_ADDRESS" >> $GITHUB_ENV

      - name: Print output
        run: |
          echo "Deploy output:"
          env | sort | grep -E 'CODE_ID|ADDRESS' > output.txt
          cat output.txt

      - name: Send output
        id: sendoutput
        run: |
          cat output.txt >> "$GITHUB_OUTPUT"
