name: Deploy

on:
  pull_request:
#  TODO uncomment when activate deployment
#  workflow_dispatch:

env:
  # Chain configuration
  CHAIN_ID: todo
  FEE_DENOM: outbe
  RPC: todo

jobs:
  deploy:
    name: Optimize Wasm And Deploy
    runs-on: ubuntu-latest
#    outputs:
#      CONTRACT_REGISTRY_CONTRACT_ADDRESS: ${{ steps.sendoutput.outputs.CONTRACT_REGISTRY_CONTRACT_ADDRESS }}
    container:
      image: ghcr.io/outbe/outbe-wasm-builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Configure wallet
        env:
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
        run: |
          outbe-noded keys import-hex ci $WALLET_PRIVATE_KEY --keyring-backend test
          OWNER_ADDRESS=$(outbe-noded keys show ci --keyring-backend test --output json | jq -r '.address')
          echo "OWNER_ADDRESS=$OWNER_ADDRESS" >> $GITHUB_ENV

      - name: Make Optimized build
        run: |
          optimize.sh .

      - name: Print output
        run: |
          echo "Deploy output:"
          env | sort | grep -E 'CODE_ID|ADDRESS' > output.txt
          cat output.txt

      - name: Send output
        id: sendoutput
        run: |
          cat output.txt >> "$GITHUB_OUTPUT"
